logging.level:
  it.mltk.kes: DEBUG

spring:
  cloud:
    stream:
      bindings:
        output:
          binder: kafka
          destination: channel-name
          contentType: application/json
          producer:
            headerMode: raw # Outbound data has no embedded headers
        input:
          destination: channel-name
          contentType: application/json
          group: project-sink
          consumer:
            useNativeDecoding: true
            headerMode: raw
      kafka:
        streams:
          binder:
            brokers: 127.0.0.1
            zkNodes: 127.0.0.1

logger.level:
  org.apache.kafka: DEBUG
  org.apache.kafka.clients: DEBUG