logging.level:
  it.mltk.kes: DEBUG

spring:
  cloud:
    stream:
      bindings:
        project-producer:
          destination: projects
        domain-event-producer:
          destination: events
        project-consumer:
          destination: projects
      kafka:
        streams:
          binder:
            brokers: 127.0.0.1
            zkNodes: 127.0.0.1

logger.level:
  org.apache.kafka: DEBUG
  org.apache.kafka.clients: DEBUG
