logging.level:
  it.mltk.kes: DEBUG

spring:
  cloud:
    stream:
      bindings:
        project-producer:
          destination: projects
        domain-event-producer:
          destination: events
          contentType: application/json
          producer:
            headerMode: raw # Outbound data has no embedded headers
        project-consumer:
          destination: projects
        domain-event-consumer:
          destination: events
          contentType: application/json
          group: domain-event-consumer-v1
          consumer:
            useNativeDecoding: true
            headerMode: raw
            startOffset: earliest
      kafka:
        streams:
          binder:
            brokers: 127.0.0.1
            zkNodes: 127.0.0.1

logger.level:
  org.apache.kafka: DEBUG
  org.apache.kafka.clients: DEBUG
